import test from "node:test"; import assert from "node:assert/strict"; import fs from "node:fs"; import ts from "typescript";
async function load(path){let source=fs.readFileSync(path,"utf8").replace(/^import type .*;$/gm,"");const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;return import(`data:text/javascript;base64,${Buffer.from(js).toString("base64")}`)}
test("verification summary counts records once and responds to evidence removal",async()=>{const {calculateVerificationSummary}=await load("lib/verification-summary.ts");let records=[{verificationStatus:"NOT_SUBMITTED",documents:[{}],evidenceLinks:[]},{verificationStatus:"PENDING",documents:[],evidenceLinks:[{}]},{verificationStatus:"VERIFIED",documents:[{},{}],evidenceLinks:[{}]}];assert.deepEqual(calculateVerificationSummary(records),{verified:1,evidenceSubmitted:2,ownerDeclared:0});records[0].documents=[];records[1].evidenceLinks=[];assert.deepEqual(calculateVerificationSummary(records),{verified:1,evidenceSubmitted:0,ownerDeclared:2})});
test("evidence URLs require public HTTPS",async()=>{const {validateEvidenceUrl}=await load("lib/evidence-links.ts");assert.equal(validateEvidenceUrl("https://www.akc.org/result/1"),"https://www.akc.org/result/1");for(const url of ["http://example.com","javascript:alert(1)","data:text/plain,no","https://localhost/a","https://127.0.0.1/a","https://10.0.0.2/a","https://192.168.1.2/a","https://172.16.0.1/a","https://169.254.1.1/a","https://[::1]/a","https://[fc00::1]/a","https://[fe80::1]/a","not a url"])assert.throws(()=>validateEvidenceUrl(url))});
test("country eligibility and genuine counts",async()=>{const m=await load("lib/competitions.ts");assert.equal(m.competitionCountryEligibility("UK_ONLY","England"),true);assert.equal(m.competitionCountryEligibility("UK_ONLY","Republic of Ireland"),false);assert.equal(m.competitionCountryEligibility("INTERNATIONAL","Republic of Ireland"),true);assert.equal(m.realEntrantCount([{status:"SUBMITTED"},{status:"WITHDRAWN"},{status:"FINALIST"}]),2);assert.equal(m.competitionAcceptsEntries("DRAFT",new Date(0),new Date(9999999999999)),false);assert.equal(m.competitionAcceptsEntries("CLOSED",new Date(0),new Date(9999999999999)),false)});
test("core completeness has no competition points or role penalty",async()=>{const source=fs.readFileSync("lib/profile-completeness.ts","utf8");assert.doesNotMatch(source,/competition|professional|breeder|rescue|foster/i);assert.match(source,/calculateDogProfileCompleteness/)});
test("support report template contains prompts and no private data",async()=>{const source=fs.readFileSync("lib/launch-config.ts","utf8");for(const prompt of ["Page or feature","What happened","What did you expect","Device","Browser","Screenshot available"])assert.match(source,new RegExp(prompt));assert.doesNotMatch(source,/password.*problemReportBody|token.*problemReportBody|dogId.*problemReportBody/i)});
test("every competition administration surface has a server-side ADMIN guard",()=>{for(const path of ["app/admin/competitions/page.tsx","app/admin/competitions/new/page.tsx","app/admin/competitions/[id]/page.tsx"]){const source=fs.readFileSync(path,"utf8");assert.match(source,/requireUser\(\)/);assert.match(source,/role\s*!==\s*["']ADMIN["']/)}const actions=fs.readFileSync("lib/competitions/actions.ts","utf8");for(const name of ["saveCompetition","moderateEntry","publishResult"])assert.match(actions,new RegExp(`export async function ${name}\\(form: FormData\\) \\{\\n  await requireAdmin\\(\\)`))});
test("entry mutation rechecks state and limits serializably",()=>{const source=fs.readFileSync("lib/competitions/actions.ts","utf8");assert.match(source,/ownerships: \{ some: \{ userId: user\.id \} \}/);assert.match(source,/isolationLevel: "Serializable"/);assert.match(source,/competitionEntry\.count/);assert.match(source,/notIn: \["WITHDRAWN", "DISQUALIFIED"\]/);assert.match(source,/competitionCountryEligibility/)});
test("competition storage keys stay behind the image route",()=>{const pages=["app/competitions/page.tsx","app/competitions/[slug]/page.tsx","app/competitions/[slug]/enter/page.tsx"].map(path=>fs.readFileSync(path,"utf8")).join("\n");assert.doesNotMatch(pages,/storageKey/);const route=fs.readFileSync("app/api/competition-images/[entryId]/route.ts","utf8");assert.match(route,/getObject\(entry\.storageKey\)/);assert.match(route,/publicAllowed/)});
test("migration preserves existing access and defaults every user to MEMBER",()=>{const migration=fs.readFileSync("prisma/migrations/20260731120000_launch_competitions_evidence_admin/migration.sql","utf8");assert.match(migration,/ADD COLUMN "role" "UserRole" NOT NULL DEFAULT 'MEMBER'/);assert.doesNotMatch(migration,/DEFAULT 'ADMIN'|SET "role" = 'ADMIN'/);assert.doesNotMatch(migration,/DROP TABLE|DROP COLUMN|DELETE FROM/);assert.match(migration,/CompetitionEntry_dogId_fkey.*ON DELETE RESTRICT/)});
