import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const read=p=>fs.readFileSync(p,"utf8");
test("premium detail uses compact event hierarchy and image modes",()=>{const s=read("app/competitions/[slug]/page.tsx");for(const text of ["Competition facts","Prizes & event","How to enter","Rules, eligibility & important dates"])assert.match(s,new RegExp(text));assert.match(s,/object-contain/);assert.match(s,/object-cover/);assert.doesNotMatch(s,/At a glance/);assert.match(s,/take:6/);assert.match(s,/<h1/)});
test("listing separates lifecycle stages and avoids zero entrant claims",()=>{const s=read("app/competitions/page.tsx");for(const text of ["Open now","Coming soon","Judging","Recently completed / winners","Entries are now open"])assert.match(s,new RegExp(text));assert.doesNotMatch(s,/\{count\} entrants/)});
test("paid entry and lifecycle are guarded without fake checkout",()=>{const s=read("lib/competitions/actions.ts");assert.match(s,/Paid entries are not available yet/);assert.match(s,/Paid competitions cannot open/)});
test("hero upload and organiser saves expose pending and duplicate prevention",()=>{const s=read("components/competition-action-form.tsx")+read("components/competition-admin-form.tsx");assert.match(s,/Uploading image…/);assert.match(s,/Selected:/);assert.match(s,/disabled=\{pending\}/);assert.match(s,/aria-live/)});
test("migration is additive and preserves legacy prize summary",()=>{const sql=read("prisma/migrations/20260807120000_premium_competition_experience/migration.sql");assert.match(sql,/ADD COLUMN/);assert.doesNotMatch(sql,/DROP|DELETE FROM/);assert.match(read("prisma/schema.prisma"),/prizeSummary\s+String/)});

test("crafted numeric requests are rejected before persistence",()=>{const s=read("lib/competitions.ts");assert.match(s,/Number\.isSafeInteger/);assert.match(s,/no more than two decimal places/);assert.match(s,/maximumPence/);const actions=read("lib/competitions/actions.ts");assert.match(actions,/parsePoundsToPence\(value\(form,"entryFeePounds"\).*100_000/);assert.match(actions,/parseBoundedInteger\(value\(form, "maxEntriesPerDog"\).*1, 20/);assert.match(actions,/parseBoundedInteger\(value\(formData,"displayOrder"\).*0,1000/)});
test("multi-dog CTA is capacity-aware rather than account-wide",()=>{const s=read("lib/competitions.ts");assert.match(s,/ownedDogIds\.some/);assert.match(s,/counts\.get\(id\).*< maxEntriesPerDog/);const page=read("app/competitions/[slug]/page.tsx");assert.match(page,/competitionEntryCtaState/);assert.match(page,/View your entries/)});
test("listing classification handles stale published and expired open states",()=>{const s=read("lib/competitions.ts");assert.match(s,/status === "OPEN".*now >= closesAt \? "judging"/);assert.match(s,/status === "PUBLISHED".*now < opensAt \? "upcoming".*"awaiting"/)});
test("prizes are editable, HTTPS-only, rendered, and fully revalidated",()=>{const admin=read("app/admin/competitions/[id]/page.tsx"),actions=read("lib/competitions/actions.ts"),page=read("app/competitions/[slug]/page.tsx");assert.match(admin,/name="prizeId" value=\{p\.id\}/);assert.match(admin,/Save prize changes/);assert.match(actions,/parsed\.protocol !== "https:"/);assert.match(page,/p\.imageUrl&&<img/);assert.ok(actions.includes('revalidatePath("/competitions")'))});
test("hero cleanup is awaited in runtimes without guaranteed background work",()=>{const s=read("lib/competitions/actions.ts");assert.match(s,/await deleteObject\(competition\.heroStorageKey\)/);assert.doesNotMatch(s,/void deleteObject\(competition\.heroStorageKey\)/)});
