import { notFound } from "next/navigation";
import { ButtonLink, Card, Section } from "@/components/ui";
import { getCurrentUser } from "@/lib/auth/session";
import { competitionAcceptsEntries, competitionIsPubliclyVisible, publicEntryStatus, realEntrantCount } from "@/lib/competitions";
import { prisma } from "@/lib/prisma";

const money=(p:number)=>p===0?"FREE ENTRY":new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(p/100)+" entry";
const lines=(s:string|null)=>s?.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)??[];
export default async function CompetitionPage({ params }: { params: { slug: string } }) {
 const user=await getCurrentUser();
 const competition=await prisma.competition.findUnique({where:{slug:params.slug},include:{prizes:{orderBy:{displayOrder:"asc"}},judges:{orderBy:{displayOrder:"asc"}},entries:{where:{status:{in:["SUBMITTED","FINALIST","WINNER"]}},include:{dog:{select:{name:true,registryNumber:true}}},orderBy:{submittedAt:"desc"}},results:{include:{entry:{include:{dog:{select:{name:true,registryNumber:true}}}}},orderBy:{placement:"asc"}}}});
 if(!competition||competition.status==="CANCELLED"||(competition.status==="DRAFT"&&user?.role!=="ADMIN"))notFound();
 const accepting=competitionAcceptsEntries(competition.status,competition.opensAt,competition.closesAt)&&competition.entryFeePence===0;
 const count=realEntrantCount(competition.entries); const gallery=competition.galleryVisible&&competitionIsPubliclyVisible(competition.status)?competition.entries.filter(e=>publicEntryStatus(e.status)&&Boolean(e.imageUseConsentAt)).slice(0,9):[];
 const days=Math.ceil((+competition.closesAt-Date.now())/86400000); const proof=count===0?(competition.launchMessage||"Entries are now open — be one of the first"):count<5?`${count} genuine ${count===1?"entry":"entries"} so far`:`Join ${count} genuine entrants`;
 const ownedDogs=user?await prisma.dogIdentity.findMany({where:{ownerships:{some:{userId:user.id}}},select:{id:true}}):[];
 const entered=user?competition.entries.some(e=>e.dog&&ownedDogs.some(d=>d.id===e.dogId)):false;
 const cta=!accepting?null:!user?{href:"/signup",label:"Create free account / Sign in"}:!ownedDogs.length?{href:"/register-dog",label:"Register your dog"}:entered?{href:`/competitions/${competition.slug}#entries`,label:"View your entry"}:{href:`/competitions/${competition.slug}/enter`,label:"Enter competition"};
 return <>
  <section className="mx-auto max-w-7xl px-4 py-5 sm:px-6 md:px-8"><div className="relative isolate min-h-[31rem] overflow-hidden rounded-[2rem] bg-navy shadow-registry sm:min-h-[34rem]">
   {competition.heroStorageKey?<img src={`/api/competition-hero/${competition.id}`} alt={competition.heroAltText||`${competition.title} competition hero`} className="absolute inset-0 h-full w-full object-cover opacity-70" style={{objectPosition:competition.heroFocalPosition}}/>:<div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,_#7facc7,_#08294a_58%)]" aria-hidden="true"/>}<div className="absolute inset-0 bg-gradient-to-t from-navy via-navy/60 to-transparent" aria-hidden="true"/>
   <div className="relative flex min-h-[31rem] max-w-3xl flex-col justify-end p-5 text-white sm:min-h-[34rem] sm:p-10"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-white px-3 py-1 text-xs font-extrabold text-navy">{money(competition.entryFeePence)}</span><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-bold">{competition.eligibility==="UK_ONLY"?"UK only":"International"}</span></div><p className="mt-4 text-sm font-bold uppercase tracking-[.18em] text-sky-100">{competition.theme}</p><h1 className="mt-2 text-4xl font-extrabold leading-tight sm:text-6xl">{competition.title}</h1>{competition.tagline&&<p className="mt-3 text-lg text-white/90 sm:text-xl">{competition.tagline}</p>}<div className="mt-5 flex flex-wrap items-center gap-3"><strong>{days>0?`${days} ${days===1?"day":"days"} remaining`:"Entries closed"}</strong><span aria-hidden="true">·</span><span>Closes {competition.closesAt.toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"})}</span></div><p className="mt-2 text-sm font-semibold text-sky-100">{proof}</p>{cta&&<div className="mt-5"><ButtonLink href={cta.href}>{cta.label}</ButtonLink></div>}</div>
  </div></section>
  {user?.role==="ADMIN"&&<div className="mx-auto flex max-w-7xl gap-2 px-4"><ButtonLink href={`/admin/competitions/${competition.id}`}>Edit competition</ButtonLink><span className="rounded-full bg-amber-100 px-4 py-3 text-sm font-bold">Admin preview · {competition.status}</span></div>}
  <Section eyebrow="At a glance" title="Everything you need to enter"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Entry",money(competition.entryFeePence)],["Eligibility",competition.eligibility==="UK_ONLY"?"United Kingdom":"Worldwide"],["Entries per dog",String(competition.maxEntriesPerDog)],["Headline prize",competition.prizes[0]?.title||competition.prizeSummary]].map(([a,b])=><Card key={a}><p className="registry-label">{a}</p><p className="mt-2 text-lg font-extrabold text-navy">{b}</p></Card>)}</div></Section>
  <Section eyebrow="The challenge" title={competition.theme}><Card><p className="max-w-4xl whitespace-pre-line text-lg leading-8 text-charcoal/80">{competition.description}</p></Card></Section>
  <Section eyebrow="Prize showcase" title="What you could win"><div className="grid gap-4 md:grid-cols-3">{competition.prizes.length?competition.prizes.map(p=><Card key={p.id}><p className="registry-label">{p.placement}</p><h2 className="mt-2 text-2xl font-extrabold text-navy">{p.title||"Prize"}</h2>{p.valuePence!=null&&<p className="mt-2 font-bold text-info">Estimated value {money(p.valuePence).replace(" entry","")}</p>}<p className="mt-3 leading-7">{p.description}</p>{p.sponsor&&<p className="mt-3 text-sm font-bold">Provided by {p.sponsor}</p>}{p.digitalAward&&<p className="mt-2 text-sm">Digital award: {p.digitalAward}</p>}</Card>):<Card><h2 className="text-xl font-bold">Competition prize</h2><p className="mt-2 leading-7">{competition.prizeSummary}</p></Card>}</div></Section>
  <Section eyebrow="Simple and secure" title="How to enter"><ol className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["Create or sign in to your Bark Booth account","Register or select your dog","Upload the competition photo","Accept the rules and image consent, then submit"].map((x,i)=><Card key={x}><span className="grid h-9 w-9 place-items-center rounded-full bg-navy font-bold text-white">{i+1}</span><p className="mt-3 font-bold">{x}</p></Card>)}</ol>{cta&&<div className="mt-5"><ButtonLink href={cta.href}>{cta.label}</ButtonLink></div>}</Section>
  <Section eyebrow="Genuine community" title="Recent entries"><div id="entries">{gallery.length?<><div className="grid gap-4 grid-cols-2 lg:grid-cols-3">{gallery.map(e=><Card key={e.id}><img src={`/api/competition-images/${e.id}`} alt={`${e.dog.name} competition entry`} className="aspect-square w-full rounded-2xl object-cover"/><h2 className="mt-3 text-lg font-bold">{e.dog.name}</h2><a className="text-sm font-bold text-info" href={`/dogs/${e.dog.registryNumber}`}>View dog profile</a></Card>)}</div><p className="mt-4 font-bold">Showing recent public, consented entries.</p></>:<Card><h2 className="text-xl font-bold">Be part of the gallery</h2><p className="mt-2">No public entries to show yet. Enter now and be one of the first.</p></Card>}</div></Section>
  {competition.judges.length>0&&<Section eyebrow="Expert panel" title="Meet the judges"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{competition.judges.map(j=><Card key={j.id}>{j.imageStorageKey&&<img src={`/api/judge-images/${j.id}`} alt={`${j.name}, competition judge`} className="h-24 w-24 rounded-full object-cover"/>}<p className="registry-label mt-3">{j.guestJudge?"Guest judge":j.roleTitle||"Judge"}</p><h2 className="mt-1 text-2xl font-bold">{j.name}</h2>{j.organisation&&<p className="font-bold text-info">{j.organisation}</p>}{j.profession&&<p className="mt-3 line-clamp-3">{j.profession}</p>}{j.judgingFocus&&<p className="mt-3"><strong>Looking for:</strong> {j.judgingFocus}</p>}</Card>)}</div></Section>}
  {competition.judgingCriteria&&<Section eyebrow="What matters" title="Judging criteria"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{lines(competition.judgingCriteria).map(x=><Card key={x}><p className="font-bold">{x}</p></Card>)}</div></Section>}
  <Section eyebrow="Please read" title="Rules and important dates"><div className="grid gap-4 lg:grid-cols-2"><Card><details><summary className="cursor-pointer text-lg font-bold">Competition rules</summary><p className="mt-4 whitespace-pre-line leading-7">{competition.rules}</p></details><details className="mt-4"><summary className="cursor-pointer text-lg font-bold">Photo guidelines</summary><p className="mt-4 whitespace-pre-line leading-7">{competition.imageGuidelines}</p></details></Card><Card><dl className="grid gap-4"><div><dt>Entries open</dt><dd>{competition.opensAt.toLocaleString("en-GB")}</dd></div><div><dt>Entries close</dt><dd>{competition.closesAt.toLocaleString("en-GB")}</dd></div><div><dt>Current stage</dt><dd className="capitalize">{competition.status.toLowerCase()}</dd></div></dl></Card></div></Section>
  {competition.results.some(r=>r.publishedAt)&&<Section eyebrow="Official results" title="Meet the winners"><div className="grid gap-4 md:grid-cols-3">{competition.results.filter(r=>r.publishedAt).map(r=><Card key={r.id}><p className="registry-label">{r.placement}. {r.title}</p><h2 className="mt-2 text-2xl font-bold">{r.entry.dog.name}</h2>{r.judgeNotes&&<p className="mt-2">{r.judgeNotes}</p>}</Card>)}</div></Section>}
  {cta&&<Section title="Ready for your dog's moment?"><Card className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><p className="text-lg font-bold">{proof}</p><ButtonLink href={cta.href}>{cta.label}</ButtonLink></Card></Section>}
 </>;
}
