"use server";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/auth/session";
import { supportedLocations, isSupportedLocation } from "@/lib/locations";
import { professionalTypes, validateServices, slugify, professionalTypeLabels, servicesByType } from "@/lib/professionals/catalog";
import { validateEvidenceUrl } from "@/lib/evidence-links";
import { putObject, deleteObject } from "@/lib/storage";
import { imageContentTypes, documentContentTypes, MAX_PROFILE_PHOTO_BYTES, MAX_RECORD_DOCUMENT_BYTES, storageKey, validateUpload } from "@/lib/uploads";
import type { ProfessionalProfilePublicationStatus, ProfessionalProfileVerificationStatus } from "@prisma/client";
const s=(v:FormDataEntryValue|null)=>typeof v==="string"?v.trim():"";
function safeHttps(v:string){ if(!v) return null; return validateEvidenceUrl(v); }
function asType(v:string){ if(!professionalTypes.includes(v as any)) throw new Error("Choose a supported professional type."); return v as any; }
async function uniqueSlug(name:string, id?:string){ const base=slugify(name); for(let i=0;i<50;i++){const slug=i?`${base}-${i+1}`:base; const found=await prisma.professionalProfile.findUnique({where:{slug},select:{id:true}}); if(!found||found.id===id) return slug;} return `${base}-${Date.now()}`; }
async function ownerProfile(id:string){ const user=await requireUser(); const p=await prisma.professionalProfile.findUnique({where:{id}}); if(!p||p.ownerUserId!==user.id) throw new Error("You can only manage Professional Profiles you own."); return {user, profile:p}; }
export async function saveProfessionalProfile(form:FormData){ const user=await requireUser(); const id=s(form.get("profileId")); const type=asType(s(form.get("type"))||"OTHER"); const businessName=s(form.get("businessName")); if(!businessName) throw new Error("Business name is required."); if(type==="OTHER"&&!s(form.get("customType"))) throw new Error("Describe the professional type when choosing Other."); const country=s(form.get("country")); if(!isSupportedLocation(country)) throw new Error("Choose a supported country."); const services=validateServices(type, form.getAll("services").map(s).filter(Boolean)); const other=s(form.get("otherService")); const data={type, customType:s(form.get("customType"))||null, businessName, shortDescription:s(form.get("shortDescription"))||"Draft profile awaiting description.", yearEstablished:s(form.get("yearEstablished"))?Number(s(form.get("yearEstablished"))):null, email:s(form.get("email"))||null, phone:s(form.get("phone"))||null, website:safeHttps(s(form.get("website"))), facebookUrl:safeHttps(s(form.get("facebookUrl"))), instagramUrl:safeHttps(s(form.get("instagramUrl"))), addressLine1:s(form.get("addressLine1"))||null, addressLine2:s(form.get("addressLine2"))||null, townCity:s(form.get("townCity"))||null, regionCounty:s(form.get("regionCounty"))||null, postcode:s(form.get("postcode"))||null, country, mobileBusiness:form.get("mobileBusiness")==="on", serviceRadiusValue:s(form.get("serviceRadiusValue"))?Number(s(form.get("serviceRadiusValue"))):null, serviceRadiusUnit:(s(form.get("serviceRadiusUnit"))==="KILOMETRES"?"KILOMETRES":"MILES") as "KILOMETRES" | "MILES", addressVisibility:["FULL_ADDRESS","TOWN_AREA_ONLY","SERVICE_AREA_ONLY"].includes(s(form.get("addressVisibility")))?s(form.get("addressVisibility")) as any:"TOWN_AREA_ONLY", hoursNote:s(form.get("hoursNote"))||null, appointmentOnly:form.get("appointmentOnly")==="on"}; const profile=id?(await ownerProfile(id)).profile:null; const saved= id ? await prisma.professionalProfile.update({where:{id},data:{...data,slug:await uniqueSlug(businessName,id),services:{deleteMany:{},create:[...services.map(label=>({serviceKey:slugify(label),label})), ...(other?[{serviceKey:`other-${slugify(other)}`,label:other,isOther:true}]:[])]},audits:{create:{actorUserId:user.id,action:"OWNER_SAVE"}}}}) : await prisma.professionalProfile.create({data:{ownerUserId:user.id,slug:await uniqueSlug(businessName),...data,services:{create:[...services.map(label=>({serviceKey:slugify(label),label})), ...(other?[{serviceKey:`other-${slugify(other)}`,label:other,isOther:true}]:[])]},audits:{create:{actorUserId:user.id,action:"OWNER_CREATE"}}}}); revalidatePath("/dashboard"); revalidatePath(`/dashboard/professionals/${saved.id}`);  }
function meetsPublishMinimum(p:any){return p.businessName&&p.shortDescription&&p.type&&(p.email||p.phone||p.website)&&(p.mobileBusiness||p.townCity||p.country);}
export async function setProfessionalPublication(form:FormData){ const {user,profile}=await ownerProfile(s(form.get("profileId"))); const to=s(form.get("to")) as ProfessionalProfilePublicationStatus; if(to==="PUBLISHED"&&!meetsPublishMinimum(profile)) throw new Error("Add a description, contact method and safe location/service area before publishing."); const data:any={publicationStatus:to}; if(to==="PUBLISHED") data.publishedAt=new Date(); if(to==="DRAFT") data.publishedAt=null; if(to==="ARCHIVED"){data.archivedAt=new Date(); data.archiveReason=s(form.get("reason"))||"Archived by owner; media and evidence retained.";} await prisma.professionalProfile.update({where:{id:profile.id},data:{...data,audits:{create:{actorUserId:user.id,action:`PUBLICATION_${to}`,reason:data.archiveReason}}}}); revalidatePath("/professionals"); revalidatePath(`/professionals/${profile.slug}`); }
export async function addProfessionalEvidence(form:FormData){ const {user,profile}=await ownerProfile(s(form.get("profileId"))); const publicUrl=s(form.get("publicUrl")); let upload:any=null; const raw=form.get("document"); if(raw instanceof File && raw.name && raw.size){ const {file,bytes}=await validateUpload(raw, documentContentTypes, MAX_RECORD_DOCUMENT_BYTES); upload={storageKey:storageKey(`professionals/${profile.id}/evidence`,file.type),fileName:file.name,contentType:file.type,sizeBytes:file.size}; await putObject(upload.storageKey,bytes,file.type); } try{await prisma.professionalProfileEvidence.create({data:{profileId:profile.id,evidenceType:s(form.get("evidenceType")) as any,title:s(form.get("title"))||"Supporting evidence",issuerProvider:s(form.get("issuerProvider"))||null,referenceNumber:s(form.get("referenceNumber"))||null,publicUrl:publicUrl?safeHttps(publicUrl):null,publicUrlVisible:form.get("publicUrlVisible")==="on",ownerNotes:s(form.get("ownerNotes"))||null,...upload}}); await prisma.professionalProfile.update({where:{id:profile.id},data:{verificationStatus:"EVIDENCE_SUBMITTED",audits:{create:{actorUserId:user.id,action:"EVIDENCE_SUBMITTED"}}}})}catch(e){ if(upload) await deleteObject(upload.storageKey); throw e;} }
export async function uploadProfessionalImage(form:FormData){ const {profile}=await ownerProfile(s(form.get("profileId"))); const kind=s(form.get("kind"))==="GALLERY"?"GALLERY":"LOGO"; if(kind==="GALLERY"){ const count=await prisma.professionalProfileMedia.count({where:{profileId:profile.id,kind:"GALLERY",active:true}}); if(count>=10) throw new Error("A Professional Profile can have up to 10 gallery images."); } const {file,bytes}=await validateUpload(form.get("image"), imageContentTypes, MAX_PROFILE_PHOTO_BYTES); const key=storageKey(`professionals/${profile.id}/${kind.toLowerCase()}`,file.type); await putObject(key,bytes,file.type); let old:string|null=null; try{ if(kind==="LOGO"){ const prev=await prisma.professionalProfileMedia.findFirst({where:{profileId:profile.id,kind:"LOGO",active:true},select:{id:true,storageKey:true}}); if(prev){old=prev.storageKey; await prisma.professionalProfileMedia.update({where:{id:prev.id},data:{active:false}});} } await prisma.professionalProfileMedia.create({data:{profileId:profile.id,kind,storageKey:key,fileName:file.name,contentType:file.type,sizeBytes:file.size,displayOrder:Number(s(form.get("displayOrder"))||0),altText:s(form.get("altText"))||null}}); }catch(e){await deleteObject(key); throw e;} if(old) await deleteObject(old); }
export async function reviewProfessionalProfile(form:FormData){ const user=await requireUser(); if(user.role!=="ADMIN") throw new Error("ADMIN access required."); const id=s(form.get("profileId")); const status=s(form.get("verificationStatus")) as ProfessionalProfileVerificationStatus; await prisma.professionalProfile.update({where:{id},data:{verificationStatus:status,verificationNotes:s(form.get("verificationNotes"))||null,adminReviewNotes:s(form.get("adminReviewNotes"))||null,reviewedById:user.id,reviewedAt:new Date(),audits:{create:{actorUserId:user.id,action:`ADMIN_${status}`,reason:s(form.get("adminReviewNotes"))||null}}}}); revalidatePath("/admin/professionals"); }
