import { createApplicationDraft } from "@/lib/role-applications/actions";
import { requireUser } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { applicationRoles, formatRole } from "@/lib/roles";
import { AccountRoleSummary, RoleApplicationCard } from "@/components/roles";
import { Card, Section } from "@/components/ui";
function formatDate(date: Date) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(date); }
export default async function AccountPage() {
  const user = await requireUser();
  const fullUser = await prisma.user.findUniqueOrThrow({ where: { id: user.id }, include: { ownerStatuses: true, roleApplications: { orderBy: { createdAt: "desc" } } } });
  const activeRoles = new Set(fullUser.roleApplications.filter((a) => ["DRAFT", "SUBMITTED", "UNDER_REVIEW", "APPROVED"].includes(a.status)).map((a) => a.requestedRole));
  return <><Section eyebrow="Account" title="Manage your Bark Booth account"><div className="grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><Card><p className="text-sm font-black uppercase tracking-[0.2em] text-terracotta">Account identity</p><h3 className="mt-2 text-2xl font-black text-navy">Bark Booth Member</h3><dl className="mt-5 grid gap-3 text-sm font-bold"><div><dt className="text-charcoal/45">Display name</dt><dd>{fullUser.displayName}</dd></div><div><dt className="text-charcoal/45">Username</dt><dd>@{fullUser.username}</dd></div><div><dt className="text-charcoal/45">Email</dt><dd>{fullUser.email}</dd></div><div><dt className="text-charcoal/45">Country</dt><dd>{fullUser.country}</dd></div><div><dt className="text-charcoal/45">Member since</dt><dd>{formatDate(fullUser.createdAt)}</dd></div></dl></Card><Card><p className="text-sm font-black uppercase tracking-[0.2em] text-terracotta">Community roles</p><h3 className="mt-2 text-2xl font-black text-navy">Current roles and applications</h3><div className="mt-5"><AccountRoleSummary ownerStatuses={fullUser.ownerStatuses} applications={fullUser.roleApplications} /></div><p className="mt-4 text-sm leading-6 text-charcoal/65">Legacy breeder, rescue, foster or professional statuses are shown as unverified until Bark Booth approves a role application.</p></Card></div></Section><Section eyebrow="Applications" title="Apply for additional verified roles"><div className="grid gap-4 md:grid-cols-2">{fullUser.roleApplications.map((app) => <RoleApplicationCard key={app.id} app={app} />)}{applicationRoles.map((role) => activeRoles.has(role) ? null : <Card key={role}><h3 className="text-xl font-black text-navy">{role === "BREEDER" ? "Apply for Breeder status" : `Apply for Verified ${formatRole(role)}`}</h3><p className="mt-2 text-sm leading-6 text-charcoal/65">Start a private application for Bark Booth review. Approval is controlled by Bark Booth, not by applicants.</p><form action={createApplicationDraft} className="mt-4"><input type="hidden" name="requestedRole" value={role} /><button className="rounded-full bg-cocoa px-5 py-3 text-sm font-black text-white">Start application</button></form></Card>)}</div></Section></>;
}
