import type { DogHeritageParent,DogVaccination } from "@prisma/client";import { Card } from "./ui";import { ManagedForm,FormSubmitButton } from "./forms/managed-form";import { removeHeritageParent,removeVaccination,saveHeritageParent,saveVaccination } from "@/lib/dogs/actions";
const date=(d:Date|null)=>d?.toISOString().slice(0,10)??"";
export function HeritageSection({dogId,parents,canManage}:{dogId:string;parents:DogHeritageParent[];canManage:boolean}){return <section id="heritage"><h2 className="text-2xl font-bold text-navy">Heritage <span className="text-sm font-normal">(optional)</span></h2><p className="mt-2 text-charcoal/65">Record only what is known. Unknown parentage is a valid state and no proof is required.</p><div className="mt-4 grid gap-4 lg:grid-cols-2">{(["MOTHER","FATHER"] as const).map(type=>{const p=parents.find(x=>x.parentType===type);return <Card key={type}><details><summary className="cursor-pointer text-xl font-bold text-navy">{type==="MOTHER"?"Mother":"Father"}: {p?.isUnknown?"Not known":p?.parentName??"Not recorded"}</summary>{canManage&&<ManagedForm action={saveHeritageParent} className="mt-4 grid gap-3"><input type="hidden" name="dogId" value={dogId}/><input type="hidden" name="parentType" value={type}/><label><input type="checkbox" name="isUnknown" defaultChecked={p?.isUnknown}/> Unknown / not known</label>{[["parentName","Parent name",p?.parentName],["barkBoothRegistryNumber","Bark Booth registry number",p?.barkBoothRegistryNumber],["breed","Breed",p?.breed],["colourMarkings","Colour / markings",p?.colourMarkings],["registryName","Registry name",p?.registryName],["registryNumber","Registry number",p?.registryNumber]].map(([n,l,v])=><label key={n} className="grid gap-1 font-bold">{l}<input name={String(n)} defaultValue={v??""} className="rounded-xl p-3"/></label>)}<label className="grid gap-1 font-bold">Registry affiliated<select name="registryAffiliated" defaultValue={p?.registryAffiliated??"UNKNOWN"} className="rounded-xl p-3"><option value="UNKNOWN">Unknown</option><option value="YES">Yes</option><option value="NO">No</option></select></label><label className="grid gap-1 font-bold">Notes<textarea name="notes" defaultValue={p?.notes??""} className="rounded-xl p-3"/></label><FormSubmitButton label="Save heritage details"/></ManagedForm>}{p&&canManage&&<ManagedForm action={removeHeritageParent} className="mt-2"><input type="hidden" name="heritageId" value={p.id}/><FormSubmitButton label="Remove" requireDirty={false}/></ManagedForm>}</details></Card>})}</div></section>}
function VaccinationForm({ dogId, item }: { dogId: string; item?: DogVaccination }) {
  return <ManagedForm action={saveVaccination} className="mt-4 grid gap-3">
    <input type="hidden" name="dogId" value={dogId}/><input type="hidden" name="vaccinationId" value={item?.id ?? ""}/>
    <label className="grid gap-1 font-bold">Vaccination name/type<input name="name" required defaultValue={item?.name} className="rounded-xl p-3"/></label>
    <label className="grid gap-1 font-bold">Vaccinated<select name="vaccinated" defaultValue={item?.vaccinated ? "YES" : "NO"} className="rounded-xl p-3"><option value="YES">Yes</option><option value="NO">No</option></select></label>
    <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 font-bold">Date administered<input type="date" name="administeredAt" defaultValue={date(item?.administeredAt ?? null)} className="rounded-xl p-3"/></label><label className="grid gap-1 font-bold">Next due date<input type="date" name="nextDueAt" defaultValue={date(item?.nextDueAt ?? null)} className="rounded-xl p-3"/></label></div>
    <label className="grid gap-1 font-bold">Veterinary practice (optional)<input name="veterinaryPractice" defaultValue={item?.veterinaryPractice ?? ""} className="rounded-xl p-3"/></label>
    <label className="grid gap-1 font-bold">Notes (optional)<textarea name="notes" defaultValue={item?.notes ?? ""} className="rounded-xl p-3"/></label>
    <FormSubmitButton label={item ? "Save vaccination changes" : "Add vaccination"}/>
  </ManagedForm>;
}

export function VaccinationSection({dogId,items,canManage}:{dogId:string;items:DogVaccination[];canManage:boolean}) {
  const now=new Date(), soon=new Date(+now+30*864e5);
  const status=(item:DogVaccination)=>!item.vaccinated?"Not vaccinated":item.nextDueAt&&item.nextDueAt<now?"Overdue":item.nextDueAt&&item.nextDueAt<=soon?"Due soon":item.nextDueAt?"Upcoming":"Completed / history";
  return <section id="vaccinations"><h2 className="text-2xl font-bold text-navy">Vaccination calendar</h2><p className="mt-2 text-charcoal/65">Dates and details are owner supplied, optional, and not clinically verified by Bark Booth.</p>
    {canManage&&<Card className="mt-4"><details><summary className="cursor-pointer font-bold">Add vaccination</summary><VaccinationForm dogId={dogId}/></details></Card>}
    <div className="mt-4 grid gap-3">{items.length?items.map(item=><Card key={item.id}><details><summary className="cursor-pointer"><div className="flex flex-wrap justify-between gap-2"><strong>{item.name}</strong><span className="font-bold text-info">{status(item)}</span></div><p className="mt-2 text-sm">Administered: {date(item.administeredAt)||"Not recorded"} · Next due: {date(item.nextDueAt)||"Not recorded"}</p><span className="mt-2 inline-flex text-sm font-bold text-navy">Manage vaccination →</span></summary>
      {item.veterinaryPractice&&<p className="mt-3 text-sm"><strong>Veterinary practice:</strong> {item.veterinaryPractice}</p>}{item.notes&&<p className="mt-2 text-sm">{item.notes}</p>}
      {canManage&&<><VaccinationForm dogId={dogId} item={item}/><div className="mt-4 rounded-xl bg-skysoft/50 p-3"><p className="text-sm font-bold text-navy">Supporting document</p><p className="mt-1 text-xs text-charcoal/65">Use the existing private Health records workflow so evidence keeps the same protected document rules.</p><a href="#records" className="mt-2 inline-flex text-sm font-bold text-info">Add or manage private vaccination evidence →</a></div><ManagedForm action={removeVaccination} className="mt-3"><input type="hidden" name="vaccinationId" value={item.id}/><FormSubmitButton label="Remove vaccination" requireDirty={false}/></ManagedForm></>}
    </details></Card>):<Card>No vaccination information recorded. Adding it is optional.</Card>}</div>
  </section>;
}
