import Link from "next/link";
import { StatusBadge } from "@/components/status-badge";
import { Card } from "@/components/ui";
import { formatRole, verifiedRoleLabels } from "@/lib/roles";
import type { RequestedRole, RoleApplicationStatus, ProfessionalCategory } from "@prisma/client";

export function RoleBadge({ label, verified = false }: { label: string; verified?: boolean }) { return <span className={`rounded-full px-4 py-2 text-sm font-black ${verified ? "bg-emerald-100 text-emerald-800" : "bg-lightgrey text-cocoa"}`}>{label}</span>; }
export function VerificationBadge({ role }: { role: RequestedRole }) { return <RoleBadge label={verifiedRoleLabels[role]} verified />; }
export function ApplicationStatusBadge({ status }: { status: RoleApplicationStatus }) { return <StatusBadge status={status} />; }
export function AccountRoleSummary({ ownerStatuses, applications }: { ownerStatuses: { status: string }[]; applications: { requestedRole: RequestedRole; status: RoleApplicationStatus }[] }) {
  const petOwner = ownerStatuses.some((s) => s.status === "PET_OWNER");
  const legacy = ownerStatuses.filter((s) => s.status !== "PET_OWNER");
  const approved = applications.filter((a) => a.status === "APPROVED");
  const pending = applications.filter((a) => ["DRAFT", "SUBMITTED", "UNDER_REVIEW", "REJECTED", "SUSPENDED"].includes(a.status));
  return <div className="flex flex-wrap gap-2"><RoleBadge label="Bark Booth Member" />{petOwner && <RoleBadge label="Pet Owner" />}{approved.map((a) => <VerificationBadge key={a.requestedRole} role={a.requestedRole} />)}{legacy.map((s) => <RoleBadge key={s.status} label={`${formatRole(s.status as RequestedRole)} — legacy unverified`} />)}{pending.map((a) => <span key={`${a.requestedRole}-${a.status}`} className="rounded-full bg-amber-100 px-4 py-2 text-sm font-black text-amber-900">{formatRole(a.requestedRole)} application — {a.status.toLowerCase().replace(/_/g, " ")}</span>)}</div>;
}
export function RoleApplicationCard({ app }: { app: { id: string; requestedRole: RequestedRole; status: RoleApplicationStatus; submittedAt: Date | null; rejectionReason: string | null } }) { return <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-black text-navy">{formatRole(app.requestedRole)} application</h3><p className="mt-1 text-sm font-bold text-charcoal/60">{app.submittedAt ? `Submitted ${app.submittedAt.toLocaleDateString("en-GB")}` : "Draft not submitted"}</p>{app.rejectionReason && <p className="mt-3 rounded-2xl bg-red-50 p-3 text-sm font-bold text-red-800">{app.rejectionReason}</p>}</div><ApplicationStatusBadge status={app.status} /></div><Link href={`/account/applications/${app.id}`} className="mt-4 inline-flex rounded-full bg-cocoa px-5 py-3 text-sm font-black text-white">{app.status === "DRAFT" || app.status === "REJECTED" ? "Continue application" : "View application"}</Link></Card>; }
export function DirectoryListingCard({ listing }: { listing: { publicDisplayName: string | null; organisationName: string | null; professionalCategory: ProfessionalCategory | null; description: string | null; serviceArea: string | null; website: string | null; email: string | null } }) { return <Card><VerificationBadge role="PROFESSIONAL" /><h3 className="mt-3 text-2xl font-black text-navy">{listing.publicDisplayName || listing.organisationName}</h3>{listing.professionalCategory && <p className="mt-1 font-black text-pink">{listing.professionalCategory.toLowerCase().replace(/_/g, " ")}</p>}<p className="mt-3 leading-7 text-charcoal/65">{listing.description}</p><div className="mt-4 grid gap-2 text-sm font-bold text-charcoal/65">{listing.serviceArea && <span>Service area: {listing.serviceArea}</span>}{listing.website && <a className="text-pink" href={listing.website}>Website</a>}{listing.email && <a className="text-pink" href={`mailto:${listing.email}`}>Contact</a>}</div></Card>; }
