import { RoleBadge, VerificationBadge } from "@/components/roles";
import { ButtonLink, Card, PawAvatar, Section, buttonStyles } from "@/components/ui";
import { requireUser } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { dashboardLocation } from "@/lib/locations";
import { approveDogAccess, cancelDogAccess, rejectDogAccess, requestDogAccess, revokeDogAccess } from "@/lib/dog-access/actions";
import { connectionDisplayName, contractedCareRelationships, dogRelationships, dualOwnershipRelationships, isDogAccessCurrentlyActive, relationshipLabels } from "@/lib/dog-access";
import { LaunchStatusBanner } from "@/components/launch-status-banner";
import { DogManagement } from "@/components/dog-management";
import { DogCard } from "@/components/dog-card";

function formatDate(date: Date) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(date); }
const accessMessages: Record<string, string> = {
  requested: "Your request is pending approval from the registered account holder.", approved: "Dog access approved.", rejected: "Dog access request rejected.", cancelled: "Request cancelled.", revoked: "Access revoked. Its history has been retained.", duplicate: "You already have an active request or approved access for that dog.", "already-owner": "That dog is already registered to your account.", "not-found": "No shareable public dog was found with that registry number.", "verified-rescue-required": "The Rescue relationship requires a currently approved Verified Rescue role.", "verified-foster-required": "The Foster relationship requires a currently approved Verified Foster role.", "verified-breeder-required": "The Breeder relationship requires a currently approved Verified Breeder role.", "verified-professional-required": "This professional relationship requires a currently approved Verified Professional role.", invalid: "Choose a valid relationship.", unauthorised: "You are not authorised to perform that action.", stale: "That request has already changed.",
};

export default async function DashboardPage({ searchParams }: { searchParams?: { access?: string } }) {
  const user = await requireUser();
  const [account, dogs, incoming, outgoing, sharedDogs, connections, professionalProfiles] = await Promise.all([
    prisma.user.findUniqueOrThrow({ where: { id: user.id }, include: { ownerStatuses: true, roleApplications: true } }),
    prisma.dogIdentity.findMany({ where: { ownerships: { some: { userId: user.id } } }, include: { profilePhoto: true, records: true, behaviourLifestyle: true, accessRequests: { where: { status: "APPROVED" }, include: { requester: { include: { roleApplications: true } } } } }, orderBy: { createdAt: "desc" } }),
    prisma.dogAccessRequest.findMany({ where: { status: "PENDING", dog: { ownerships: { some: { userId: user.id } } } }, include: { dog: true, requester: true }, orderBy: { createdAt: "desc" } }),
    prisma.dogAccessRequest.findMany({ where: { requesterUserId: user.id }, include: { dog: true }, orderBy: { createdAt: "desc" } }),
    prisma.dogAccessRequest.findMany({ where: { requesterUserId: user.id, status: "APPROVED" }, include: { dog: true, requester: { include: { roleApplications: true } }, reviewedBy: true }, orderBy: { reviewedAt: "desc" } }),
    prisma.dogAccessRequest.findMany({ where: { status: "APPROVED", dog: { ownerships: { some: { userId: user.id } } } }, include: { dog: true, requester: { include: { roleApplications: true } }, reviewedBy: true }, orderBy: { reviewedAt: "desc" } }),
    prisma.professionalProfile.findMany({ where: { ownerUserId: user.id }, include: { media: { where: { kind: "LOGO", active: true }, take: 1 } }, orderBy: { createdAt: "desc" } }),
  ]);
  const petOwner = account.ownerStatuses.some((status) => status.status === "PET_OWNER");
  const approvedRoles = account.roleApplications.filter((application) => application.status === "APPROVED");
  const feedback = searchParams?.access ? accessMessages[searchParams.access] : null;
  const activeSharedDogs = sharedDogs.filter(isDogAccessCurrentlyActive);
  const activeConnections = connections.filter(isDogAccessCurrentlyActive);
  return <><div className="mx-auto max-w-7xl px-5 pt-6"><LaunchStatusBanner /></div>
    <Section eyebrow="Owner workspace" title={`Welcome back, ${user.displayName}`}>{user.role === "ADMIN" && <Card className="mb-5"><h2 className="text-xl font-bold text-navy">Competition administration</h2><p className="mt-2">Create, schedule, review and publish competitions from visible controls.</p><div className="mt-4 flex flex-wrap gap-2"><ButtonLink href="/admin/competitions">Manage competitions</ButtonLink><ButtonLink href="/admin/competitions/new" variant="secondary">Create competition</ButtonLink><ButtonLink href="/admin/community" variant="secondary">Manage News & Events</ButtonLink></div></Card>}<div className="grid gap-4 md:grid-cols-3">
      <Card><p className="registry-label">Registered identities</p><p className="mt-2 text-3xl font-extrabold text-navy">{dogs.length}</p><p className="mt-1 text-sm text-slate">{dogs.length === 1 ? "Dog in your care" : "Dogs in your care"}</p></Card>
      <Card><p className="registry-label">Account standing</p><div className="mt-3 flex flex-wrap gap-2">{petOwner && <RoleBadge label="Pet Owner" />}{approvedRoles.map((application) => <VerificationBadge key={application.id} role={application.requestedRole} />)}{!petOwner && !approvedRoles.length && <span className="font-bold text-slate">Standard account</span>}</div></Card>
      <Card><p className="registry-label">Your details</p><p className="mt-2 font-bold text-navy">{dashboardLocation(user.country)}</p><p className="mt-1 text-sm text-slate">Member since {formatDate(user.createdAt)}</p></Card>
    </div></Section>

    <section id="professional-profiles" className="scroll-mt-24"><Section eyebrow="Professional Profiles" title="My Professional Profiles"><Card><p className="text-sm leading-6 text-charcoal/65">A Professional Profile represents a business or professional service managed from your normal Bark Booth account. Publishing is separate from Bark Booth verification.</p><div className="mt-4"><ButtonLink href="/dashboard/professionals/new">Create Professional Profile</ButtonLink></div></Card>{professionalProfiles.length ? <div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{professionalProfiles.map((profile) => <Card key={profile.id}><div className="flex items-start gap-3"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-skysoft font-extrabold text-navy">{profile.businessName.slice(0,2).toUpperCase()}</div><div><h3 className="text-xl font-bold text-navy">{profile.businessName}</h3><p className="text-sm font-bold text-info">{profile.type.replace(/_/g, " ").toLowerCase()} · {profile.publicationStatus} · {profile.verificationStatus}</p><p className="mt-1 text-sm text-charcoal/65">{profile.mobileBusiness ? "Mobile business" : [profile.townCity, profile.country].filter(Boolean).join(", ")}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{profile.publicationStatus === "PUBLISHED" && <ButtonLink href={`/professionals/${profile.slug}`} variant="secondary">View public profile</ButtonLink>}<ButtonLink href={`/dashboard/professionals/${profile.id}`} variant="secondary">Manage profile</ButtonLink></div></Card>)}</div> : null}</Section></section>
    <section id="my-dogs" className="scroll-mt-24"><Section eyebrow="Dog management" title="Find and manage your dogs">{dogs.length ? <DogManagement dogs={dogs.map((dog) => ({ id: dog.id, name: dog.name, nickname: dog.nickname, registryNumber: dog.registryNumber, visibility: dog.visibility, hasPhoto: Boolean(dog.profilePhoto), photoVersion: dog.profilePhoto?.updatedAt.toISOString() }))} /> : <Card className="border-dashed border-navy/20 bg-white"><div className="text-center"><h2 className="text-2xl font-bold text-navy">Create your first canine identity</h2><p className="mt-2 text-slate">A name and sex are enough to begin. All other information is optional.</p><div className="mt-5"><ButtonLink href="/register-dog">Register a dog</ButtonLink></div></div></Card>}</Section></section>
    <section id="shared-dogs" className="scroll-mt-24"><Section eyebrow="Authorised access" title="Shared Dogs"><div className="grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><Card><h3 className="text-2xl font-bold text-navy">Request access to a dog</h3><p className="mt-2 text-sm leading-6 text-charcoal/65">Enter a public dog&apos;s Bark Booth registry number. This creates a pending request only; the registered account holder must approve it.</p><form action={requestDogAccess} className="mt-5 grid gap-3"><label className="grid gap-1 font-bold text-navy">Registry number<input name="registryNumber" required placeholder="Bark Booth registry number" className="rounded-2xl p-3" /></label><label className="grid gap-1 font-bold text-navy">Relationship<select name="relationship" required defaultValue="" className="rounded-2xl p-3"><option value="" disabled>Choose relationship</option>{dogRelationships.map((relationship) => <option key={relationship} value={relationship}>{relationshipLabels[relationship]}</option>)}</select></label><p className="text-xs font-bold text-charcoal/55">Approved requests use View access by default. Knowing a registry number does not grant access.</p><button className={`${buttonStyles.primary} rounded-full px-5 py-3 text-sm font-bold`} type="submit">Request Dog Access</button></form></Card><div className="grid gap-4">{activeSharedDogs.length ? activeSharedDogs.map((access) => <Card key={access.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-2xl font-bold text-navy">{access.dog.name}</h3><p className="font-bold text-info">{access.dog.registryNumber}</p></div><RoleBadge label="Approved" verified /></div><p className="mt-3 font-bold text-charcoal/70">Shared as: {relationshipLabels[access.requestedRelationship]}</p><p className="mt-1 text-sm text-charcoal/65">Access level: {access.requestedAccessLevel.toLowerCase()} · {access.reviewedBy ? `Approved by ${access.reviewedBy.displayName}` : "Approved by an authorised account holder"}</p><div className="mt-4"><ButtonLink href={`/dogs/${access.dog.registryNumber}`} variant="secondary">View Dog</ButtonLink></div></Card>) : <Card><h3 className="text-xl font-bold text-navy">No approved Shared Dogs</h3><p className="mt-2 text-sm leading-6 text-charcoal/65">Dogs appear here only after an authorised holder approves a request.</p></Card>}</div></div></Section></section>
    <section id="dog-access-requests" className="scroll-mt-24"><Section eyebrow="Private account controls" title="Dog Access Requests">{feedback && <p className="mb-5 rounded-2xl bg-skysoft/50 p-4 font-bold text-navy" role="status">{feedback}</p>}<div className="grid gap-5 lg:grid-cols-2"><Card><h3 className="text-2xl font-bold text-navy">Incoming pending requests</h3><div className="mt-4 grid gap-3">{incoming.length ? incoming.map((request) => <div key={request.id} className="rounded-2xl bg-lightgrey p-4"><p className="font-bold text-navy">{request.dog.name}</p><p className="mt-1 text-sm text-charcoal/70">{request.requester.displayName} · {relationshipLabels[request.requestedRelationship]} · {request.requestedAccessLevel.toLowerCase()}</p><div className="mt-3 flex gap-2"><form action={approveDogAccess}><input type="hidden" name="requestId" value={request.id} /><button className={`${buttonStyles.success} rounded-full px-4 py-2 text-sm`} type="submit">Approve</button></form><form action={rejectDogAccess}><input type="hidden" name="requestId" value={request.id} /><button className={`${buttonStyles.danger} rounded-full px-4 py-2 text-sm`} type="submit">Reject</button></form></div></div>) : <p className="text-sm text-charcoal/60">No incoming requests.</p>}</div></Card><Card><h3 className="text-2xl font-bold text-navy">My outgoing requests</h3><div className="mt-4 grid gap-3">{outgoing.length ? outgoing.map((request) => <div key={request.id} className="rounded-2xl bg-lightgrey p-4"><p className="font-bold text-navy">{request.dog.name}</p><p className="mt-1 text-sm text-charcoal/70">{relationshipLabels[request.requestedRelationship]} · {request.status.toLowerCase()}</p>{request.status === "PENDING" && <form action={cancelDogAccess} className="mt-3"><input type="hidden" name="requestId" value={request.id} /><button className={`${buttonStyles.secondary} rounded-full px-4 py-2 text-sm`} type="submit">Cancel request</button></form>}</div>) : <p className="text-sm text-charcoal/60">No outgoing requests.</p>}</div></Card></div>{activeConnections.length > 0 && <Card className="mt-5"><h3 className="text-2xl font-bold text-navy">Current approved access connections</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{activeConnections.map((connection) => <div key={connection.id} className="rounded-2xl bg-lightgrey p-4"><p className="font-bold text-navy">{connection.dog.name}</p><p className="mt-1 text-sm text-charcoal/70">{connectionDisplayName(connection.requester, connection.requestedRelationship)} · {relationshipLabels[connection.requestedRelationship]} · {connection.requestedAccessLevel.toLowerCase()} · approved</p><form action={revokeDogAccess} className="mt-3"><input type="hidden" name="requestId" value={connection.id} /><button className={`${buttonStyles.danger} rounded-full px-4 py-2 text-sm`} type="submit">Revoke access</button></form></div>)}</div></Card>}</Section></section>
  </>;
}
